# Generated by Django 4.1.7 on 2023-03-30 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_costumer_state'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Costumer',
            new_name='Custumer',
        ),
    ]
