# Generated by Django 4.1.7 on 2023-03-30 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_rename_costumer_custumer'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Custumer',
            new_name='Customer',
        ),
    ]
